import './globals.css'
import { Inconsolata } from 'next/font/google'
import { Metadata } from 'next';
import Link from 'next/link';

const inter = Inconsolata({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + "flex min-h-screen flex-col mx-10 bg-green1 whs"}>
        <nav className='my-5'>
          <Link href={''}>Hello World</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
